const data=globalThis.SLIDES_DATA||[];
const deck=document.querySelector('.deck');
const facts=s=>s.facts?.length?`<div class="facts">${s.facts.map(([a,b],i)=>`<article class="fragment" style="--i:${i}"><b>${a}</b><span>${b}</span></article>`).join('')}</div>`:'';
const figure=s=>s.kind==='image'?`<figure class="science"><img src="${s.image}" alt="${s.title}"><figcaption>${s.caption||'Figura conceptual original para esta clase'}</figcaption></figure>`:s.diagram?`<div class="visual-svg">${diagramFor(s.diagram)}</div>`:'';
const notes=s=>`<aside class="notes"><h3>${s.title}</h3>${s.notes.map(p=>`<p>${p}</p>`).join('')}<p class="source">[Sources] ${s.source}</p></aside>`;
function render(s){if(s.kind==='cover')return `<section class="slide cover dark" data-section="${s.section}"><img class="bg" src="${s.image}" alt="Sistema digestivo humano como red bioeléctrica"><div class="shade"></div><div class="hero"><p class="eyebrow reveal">${s.eyebrow}</p><h1 class="reveal d1">Eje digestivo<br><span>modelo quíntuple</span></h1><p class="lead reveal d2">${s.lead}</p></div>${notes(s)}</section>`;
const hasVisual=!!(s.image||s.diagram);return `<section class="slide ${s.theme||''}" data-section="${s.section}"><div class="${hasVisual?'cols':''}"><div class="copy"><p class="eyebrow reveal">${s.eyebrow}</p><h2 class="reveal d1">${s.title}</h2>${s.lead?`<p class="lead reveal d2">${s.lead}</p>`:''}${facts(s)}${s.callout?`<div class="callout fragment">${s.callout}</div>`:''}${s.question?`<div class="question fragment"><b>PREGUNTA</b>${s.question}</div>`:''}</div>${hasVisual?`<div class="visual reveal d2">${figure(s)}</div>`:''}</div>${notes(s)}</section>`}
deck.innerHTML=data.map(render).join('');
const slides=[...document.querySelectorAll('.slide')],panel=document.querySelector('.notes-panel');
slides.forEach((slide,i)=>{const chrome=document.createElement('div');chrome.className='chrome';chrome.innerHTML=`<span>${slide.dataset.section}</span><span class="brand"><img src="assets/logo-regulacion-bioelectrica.png" alt="Regulación Bioeléctrica"><em>${String(i+1).padStart(2,'0')}</em></span>`;slide.prepend(chrome);[...slide.querySelectorAll('.diagram .node,.diagram .channel,.diagram .door,.diagram .ratchet,.diagram .zone,.diagram .stepNode,.diagram .questionNode,.diagram .practiceNode')].forEach((el,n)=>el.style.setProperty('--i',n));slide.querySelectorAll('.fragment').forEach(f=>f.setAttribute('aria-hidden','true'))});
let index=Math.max(0,Math.min(slides.length-1,Number(location.hash.slice(1))-1||0)),timer;
function fragments(s){return [...s.querySelectorAll('.fragment')]}
function show(n,push=true){const next=Math.max(0,Math.min(slides.length-1,n)),old=slides.find(s=>s.classList.contains('active'));clearTimeout(timer);slides.forEach(s=>s.classList.remove('leaving','enter-forward','enter-backward','exit-forward','exit-backward'));const dir=next<index?'backward':'forward';if(old&&old!==slides[next]){old.classList.remove('active');old.classList.add('leaving',`exit-${dir}`)}index=next;slides[index].classList.add('active',`enter-${dir}`);slides.forEach((s,i)=>{if(i!==index)fragments(s).forEach(f=>{f.classList.remove('visible');f.setAttribute('aria-hidden','true')})});timer=setTimeout(()=>slides.forEach(s=>s.classList.remove('leaving','enter-forward','enter-backward','exit-forward','exit-backward')),700);panel.innerHTML=slides[index].querySelector('.notes')?.innerHTML||'';document.querySelector('.progress').style.width=`${(index+1)/slides.length*100}%`;document.querySelector('.counter').textContent=`${String(index+1).padStart(2,'0')} / ${slides.length}`;if(push)history.replaceState(null,'',`#${index+1}`)}
function next(){const f=fragments(slides[index]).find(x=>!x.classList.contains('visible'));if(f){f.classList.add('visible');f.setAttribute('aria-hidden','false')}else show(index+1)}
function prev(){const v=fragments(slides[index]).filter(x=>x.classList.contains('visible'));if(v.length){const f=v.at(-1);f.classList.remove('visible');f.setAttribute('aria-hidden','true')}else show(index-1)}
document.addEventListener('keydown',e=>{if(['ArrowRight','ArrowDown',' ','PageDown'].includes(e.key)){e.preventDefault();next()}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();prev()}if(e.key==='Home')show(0);if(e.key==='End')show(slides.length-1);if(e.key.toLowerCase()==='n')panel.classList.toggle('open');if(e.key.toLowerCase()==='f')document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();if(e.key==='Escape')panel.classList.remove('open')});
document.addEventListener('click',e=>{if(e.target.closest('.notes-panel,.controls'))return;e.clientX>innerWidth*.52?next():prev()});window.addEventListener('hashchange',()=>show(Number(location.hash.slice(1))-1,false));show(index,false);
